[package]
name = "warpgatesh-agent"
description = "Per-user synchronization agent for WarpgateSH"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde_json.workspace = true
warpgatesh-core = { path = "../warpgatesh-core" }
warpgatesh-runtime = { path = "../warpgatesh-runtime" }

[lints]
workspace = true
