use std::collections::HashSet;
use std::time::{SystemTime, UNIX_EPOCH};

use warpgatesh_core::aliases::allocate_aliases;
use warpgatesh_core::ssh_config::render_profile;

use crate::RuntimeError;
use crate::api::ApiClient;
use crate::keychain::TokenStore;
use crate::ssh::manual_host_aliases;
use crate::storage::{LocalStore, SNAPSHOT_SCHEMA_VERSION, Snapshot, SyncedTarget, atomic_write};

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SyncReport {
    pub profile_count: usize,
    pub target_count: usize,
    pub added: usize,
    pub removed: usize,
    pub synchronized_at_epoch_seconds: u64,
}

/// Synchronize every configured profile and atomically replace the managed SSH
/// configuration only after every Warpgate response succeeds.
///
/// # Errors
///
/// Returns [`RuntimeError`] without changing the managed SSH configuration when
/// any profile, token, API response, host-key pin, or render step fails.
pub fn synchronize_all(
    store: &LocalStore,
    token_store: &impl TokenStore,
) -> Result<SyncReport, RuntimeError> {
    let mut catalog = store.load_profiles()?;
    if catalog.profiles.is_empty() {
        return Err(RuntimeError::InvalidInput(
            "no Warpgate profile is configured".to_owned(),
        ));
    }

    let blocked_aliases = manual_host_aliases(store.paths())?;
    let default_profile = catalog.default_profile.clone();
    let mut rendered =
        String::from("# Generated by WarpgateSH. Changes will be replaced automatically.\n\n");
    let mut synchronized_targets = Vec::new();

    for profile in &mut catalog.profiles {
        let pinned_keys = store.paths().known_hosts_directory.join(&profile.name);
        if !pinned_keys.exists() {
            return Err(RuntimeError::InvalidInput(format!(
                "profile '{}' has no pinned SSH host key; add the profile again",
                profile.name
            )));
        }

        let token = token_store.get(&profile.name)?;
        let client = ApiClient::new(&profile.base_url)?;
        let metadata = client.validate(&token)?;
        let targets = client.ssh_targets(&token)?;

        profile.username = metadata.username;
        profile.warpgate_version = metadata.version;

        let is_default = default_profile.as_deref() == Some(profile.name.as_str());
        rendered.push_str(&render_profile(
            profile,
            is_default,
            &targets,
            &blocked_aliases,
        )?);
        rendered.push('\n');

        for (target, aliases) in targets.iter().zip(
            allocate_aliases(&profile.name, is_default, &targets)
                .map_err(warpgatesh_core::ssh_config::SshConfigError::from)?,
        ) {
            let short_alias = aliases
                .short
                .filter(|short| !blocked_aliases.contains(&short.to_ascii_lowercase()));
            synchronized_targets.push(SyncedTarget {
                profile: profile.name.clone(),
                target_id: target.id.clone(),
                name: target.name.clone(),
                short_alias,
                qualified_alias: aliases.qualified,
            });
        }
    }

    synchronized_targets.sort_by(|left, right| {
        left.profile
            .cmp(&right.profile)
            .then_with(|| left.name.cmp(&right.name))
    });
    let synchronized_at_epoch_seconds = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let previous = store.load_snapshot()?;
    let previous_ids = snapshot_ids(previous.as_ref());
    let current_ids: HashSet<_> = synchronized_targets
        .iter()
        .map(|target| (target.profile.as_str(), target.target_id.as_str()))
        .collect();
    let added = current_ids.difference(&previous_ids).count();
    let removed = previous_ids.difference(&current_ids).count();

    let snapshot = Snapshot {
        schema_version: SNAPSHOT_SCHEMA_VERSION,
        synchronized_at_epoch_seconds,
        targets: synchronized_targets,
    };

    atomic_write(store.paths().ssh_config.as_path(), rendered.as_bytes())?;
    store.save_snapshot(&snapshot)?;
    store.save_profiles(&catalog)?;

    Ok(SyncReport {
        profile_count: catalog.profiles.len(),
        target_count: snapshot.targets.len(),
        added,
        removed,
        synchronized_at_epoch_seconds,
    })
}

fn snapshot_ids(snapshot: Option<&Snapshot>) -> HashSet<(&str, &str)> {
    snapshot
        .into_iter()
        .flat_map(|snapshot| &snapshot.targets)
        .map(|target| (target.profile.as_str(), target.target_id.as_str()))
        .collect()
}

#[cfg(test)]
mod tests {
    use std::collections::HashMap;
    use std::fs;
    use std::io::{Read, Write};
    use std::net::TcpListener;
    use std::sync::Mutex;
    use std::thread;

    use tempfile::TempDir;
    use warpgatesh_core::paths::WarpgatePaths;
    use warpgatesh_core::profiles::{Profile, ProfileCatalog};

    use super::*;

    #[derive(Default)]
    struct MemoryTokens(Mutex<HashMap<String, String>>);

    impl TokenStore for MemoryTokens {
        fn set(&self, profile: &str, token: &str) -> Result<(), RuntimeError> {
            self.0
                .lock()
                .expect("tokens")
                .insert(profile.to_owned(), token.to_owned());
            Ok(())
        }

        fn get(&self, profile: &str) -> Result<String, RuntimeError> {
            self.0
                .lock()
                .expect("tokens")
                .get(profile)
                .cloned()
                .ok_or_else(|| RuntimeError::Keychain("missing test token".to_owned()))
        }

        fn delete(&self, profile: &str) -> Result<(), RuntimeError> {
            self.0.lock().expect("tokens").remove(profile);
            Ok(())
        }
    }

    fn mock_warpgate() -> (String, thread::JoinHandle<()>) {
        let listener = TcpListener::bind("127.0.0.1:0").expect("mock listener");
        let address = listener.local_addr().expect("mock address");
        let responses = [
            r#"{"version":"0.27.0","username":"gregory","external_hosts":{"ssh":"ssh.example"},"ports":{"ssh":2222}}"#,
            r#"[{"id":"target-1","name":"db","kind":"Ssh"},{"id":"target-2","name":"web","kind":"Http"}]"#,
        ];
        let handle = thread::spawn(move || {
            for body in responses {
                let (mut stream, _) = listener.accept().expect("accept request");
                let mut request = [0_u8; 8192];
                let _ = stream.read(&mut request).expect("read request");
                write!(
                    stream,
                    "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{body}",
                    body.len()
                )
                .expect("write response");
            }
        });
        (format!("http://{address}/"), handle)
    }

    #[test]
    fn replaces_the_snapshot_after_all_responses_succeed() {
        let home = TempDir::new().expect("temporary home");
        let paths = WarpgatePaths::for_home(home.path());
        let store = LocalStore::new(paths.clone());
        let (base_url, server) = mock_warpgate();
        let mut catalog = ProfileCatalog::default();
        catalog
            .upsert(Profile {
                name: "lab".to_owned(),
                base_url,
                username: "pending".to_owned(),
                warpgate_version: None,
                ssh_host: "10.60.0.17".to_owned(),
                ssh_port: 22,
            })
            .expect("profile");
        store.save_profiles(&catalog).expect("save profiles");
        atomic_write(&paths.known_hosts_directory.join("lab"), b"pinned-key\n")
            .expect("pinned key");
        let tokens = MemoryTokens::default();
        tokens.set("lab", "secret").expect("test token");

        let report = synchronize_all(&store, &tokens).expect("synchronization");
        server.join().expect("mock server");

        assert_eq!(report.target_count, 1);
        assert_eq!(report.added, 1);
        let saved_profile = store
            .load_profiles()
            .expect("saved profiles")
            .profiles
            .remove(0);
        assert_eq!(saved_profile.ssh_host, "10.60.0.17");
        assert_eq!(saved_profile.ssh_port, 22);
        let config = fs::read_to_string(paths.ssh_config).expect("managed config");
        assert!(config.contains("Host db db.lab"));
        assert!(!config.contains("Host web"));
        assert_eq!(
            store.load_snapshot().expect("snapshot").unwrap().targets[0].name,
            "db"
        );
    }
}
