[package]
name = "warpgatesh-cli"
description = "Command-line interface for WarpgateSH"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "warpgatesh"
path = "src/main.rs"

[dependencies]
rpassword.workspace = true
warpgatesh-core = { path = "../warpgatesh-core" }
warpgatesh-runtime = { path = "../warpgatesh-runtime" }

[dev-dependencies]
tempfile = "3.27.0"

[lints]
workspace = true
